spring.profiles.include:
    - local

server:
    port: 8081
    servlet.contextPath: /


# csv database files
data:
    path: data/
    files:
        lines: lines.csv
        delays: delays.csv
        times: times.csv
        stops: stops.csv
    headers:
        line_id: line_id
        line_name: line_name
        delay: delay
        stop_id: stop_id
        time: time
        x_coord: x
        y_coord: y
